spring.application.name=tesis
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/tesis_db

spring.datasource.username=${SUPABASE_DB_USER:postgres}
spring.datasource.password=${SUPABASE_DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${JWT_SECRET:jwtSecret}

